import config

CURRENCY_API_URL_BASE = "https://api.currencyapi.com/v3"
CURRENCY_API_URL_STATUS = CURRENCY_API_URL_BASE + "/status"
CURRENCY_API_URL_CURRENCIES = CURRENCY_API_URL_BASE + "/currencies"
CURRENCY_API_URL_LATEST = CURRENCY_API_URL_BASE + "/latest"

API_KEY_STRING = f"?apikey={config.CURRENCY_API_KEY}"